import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * The `api` sidebar is populated automatically by `docusaurus-plugin-typedoc`
 * (see `typedoc-sidebar.ts` in `docs/api/`). We reference it via the
 * generated file at build time.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['intro', 'quickstart']
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: ['guides/optimization', 'guides/examples', 'guides/benchmarks']
    },
    {
      type: 'category',
      label: 'Editor Primitives',
      collapsed: false,
      items: [
        'editor-primitives/reorder',
        'editor-primitives/external-sync',
        'editor-primitives/discriminator-host',
        'editor-primitives/ghost-rows',
        'editor-primitives/custom-row-renderer'
      ]
    },
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'doc', id: 'api/index' },
      items: [{ type: 'autogenerated', dirName: 'api' }]
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: true,
      items: [
        'architecture/workspace',
        'architecture/testing',
        {
          type: 'category',
          label: 'Decision Records',
          link: { type: 'doc', id: 'architecture/decisions/index' },
          items: [
            'architecture/decisions/pnpm-workspaces',
            'architecture/decisions/oxlint-oxfmt',
            'architecture/decisions/esm-modules',
            'architecture/decisions/vitest-over-jest',
            'architecture/decisions/changesets'
          ]
        }
      ]
    },
    'contributing'
  ]
};

export default sidebars;
