import { z } from 'zod';
import type { FormField } from '@zod-to-form/core';
import { buildConfigSource } from '@zod-to-form/codegen';
import { FIELD_COMPONENT_NAMES } from '@zod-to-form/react';
import type { PlaygroundConfig, ComponentMapType } from '../types/playground.ts';

export type ConfigParseResult =
  | { ok: true; config: PlaygroundConfig }
  | { ok: false; error: string };

/** Available component names derived from the actual defaultComponentMap */
const COMPONENT_OPTIONS = FIELD_COMPONENT_NAMES as readonly [string, ...string[]];

/**
 * Per-field config schema — each field in the user's schema gets
 * one of these in the config Form.
 */
const fieldConfigSchema = z.object({
  component: z.enum(COMPONENT_OPTIONS).optional(),
  label: z.string().optional(),
  placeholder: z.string().optional(),
  order: z.coerce.number().optional(),
  hidden: z.boolean().optional(),
  gridColumn: z.string().optional()
});

type FieldConfigEntry = z.infer<typeof fieldConfigSchema>;

/** Components section — mirrors ComponentsConfig from core */
const componentsSchema = z.object({
  source: z.string().optional(),
  preset: z.enum(['shadcn', 'html']).optional()
});

/** Defaults section — mirrors ConfigDefaults from core */
const defaultsSchema = z.object({
  mode: z.enum(['submit', 'auto-save']).optional(),
  ui: z.enum(['shadcn', 'html']).optional(),
  overwrite: z.boolean().optional(),
  serverAction: z.boolean().optional(),
  formProvider: z.boolean().optional()
});

/**
 * Generate a dynamic Zod schema for z2f.config editing, mirroring the
 * full defineConfig({...}) shape as generated by the CLI `init` command:
 * { components: { ... }, defaults: { ... }, fields?: { ... } }
 */
export function generateConfigSchema(fields: FormField[] | null): z.ZodObject {
  const fieldsShape: Record<string, z.ZodOptional<typeof fieldConfigSchema>> = {};
  if (fields) {
    for (const field of fields) {
      fieldsShape[field.key] = fieldConfigSchema.optional();
    }
  }

  return z.object({
    components: componentsSchema.optional(),
    defaults: defaultsSchema.optional(),
    fields: z.object(fieldsShape).optional()
  });
}

/**
 * Compile-time conformance check: the schema output shape must be
 * assignable to the form values shape consumed by formValuesToConfig.
 * If the schema and the conversion functions drift apart, this will
 * produce a type error here rather than at runtime.
 */
type _ConfigSchemaOutput = z.output<ReturnType<typeof generateConfigSchema>>;
type _ConfigFormValues = Parameters<typeof formValuesToConfig>[0];
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _ConformanceCheck = _ConfigSchemaOutput extends _ConfigFormValues ? true : never;

/**
 * Filter a PlaygroundConfig's fields to only include keys present in
 * the current schema's FormField[] output. Orphaned overrides (keys
 * that no longer exist in the current schema) are silently dropped to
 * prevent stale config entries from accumulating.
 */
export function filterOrphanedOverrides(
  config: PlaygroundConfig | null,
  fields: FormField[] | null
): PlaygroundConfig | null {
  if (!config?.fields || !fields) return config;

  const validKeys = new Set(fields.map((f) => f.key));
  const filtered: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(config.fields)) {
    if (validKeys.has(key)) {
      filtered[key] = value;
    }
  }

  return { ...config, fields: filtered };
}

/**
 * Default config values matching the CLI `init` output.
 * These are always populated so they're visible in the .ts source.
 */
function getInitDefaults(componentMap: ComponentMapType) {
  const isShadcn = componentMap === 'shadcn';
  return {
    components: {
      source: isShadcn ? './components/ui' : './components',
      preset: isShadcn ? ('shadcn' as const) : undefined
    },
    defaults: {
      mode: 'submit' as const,
      ui: isShadcn ? ('shadcn' as const) : ('html' as const),
      overwrite: false,
      serverAction: false,
      formProvider: false
    }
  };
}

/**
 * Convert a PlaygroundConfig into form default values matching the
 * full defineConfig schema shape. The components and defaults sections
 * are always populated with init-style values (matching `z2f init`
 * output) so they're visible and editable in the .ts source.
 */
export function configToFormValues(
  config: PlaygroundConfig | null,
  fields: FormField[] | null,
  componentMap: ComponentMapType = 'default'
): Record<string, unknown> {
  const fieldEntries = config?.fields ?? {};
  const fieldValues: Record<string, FieldConfigEntry | undefined> = {};

  if (fields) {
    for (const field of fields) {
      // fieldEntries values are Record<string, unknown> from PlaygroundConfig; narrow to FieldConfigEntry
      fieldValues[field.key] = fieldEntries[field.key] as FieldConfigEntry | undefined;
    }
  }

  const init = getInitDefaults(componentMap);

  return {
    components: { ...init.components, ...config?.components },
    defaults: { ...init.defaults, ...config?.defaults },
    fields: fieldValues
  };
}

/**
 * Convert form values back to a PlaygroundConfig.
 * Empty/undefined entries are omitted.
 */
export function formValuesToConfig(
  values: Record<string, unknown>,
  existingConfig: PlaygroundConfig | null
): PlaygroundConfig {
  const rawComponents = (values.components ?? {}) as Record<string, unknown>;
  const rawDefaults = (values.defaults ?? {}) as Record<string, unknown>;
  const rawFields = (values.fields ?? {}) as Record<string, FieldConfigEntry | undefined>;

  // Filter out undefined component values
  const components: Record<string, unknown> = {};
  for (const [key, val] of Object.entries(rawComponents)) {
    if (val !== undefined) {
      components[key] = val;
    }
  }

  // Filter out undefined default values
  const defaults: Record<string, unknown> = {};
  for (const [key, val] of Object.entries(rawDefaults)) {
    if (val !== undefined) {
      defaults[key] = val;
    }
  }

  // Filter out empty field entries
  const fields: Record<string, unknown> = {};
  for (const [key, entry] of Object.entries(rawFields)) {
    if (!entry) continue;
    const hasValue = Object.values(entry).some((v) => v !== undefined);
    if (hasValue) {
      fields[key] = entry;
    }
  }

  return {
    ...existingConfig,
    components: Object.keys(components).length > 0 ? components : undefined,
    defaults: Object.keys(defaults).length > 0 ? defaults : undefined,
    fields: Object.keys(fields).length > 0 ? fields : undefined
  };
}

/**
 * Serialize a PlaygroundConfig to a full z2f.config.ts TypeScript source,
 * matching the output of `z2f init`. Uses buildConfigSource from codegen.
 */
export function serializeConfigToTs(
  config: PlaygroundConfig | null,
  componentMap: ComponentMapType = 'default'
): string {
  const init = getInitDefaults(componentMap);
  const components = { ...init.components, ...config?.components };
  const defaults = { ...init.defaults, ...config?.defaults };

  return buildConfigSource({
    componentSource: (components.source as string) ?? init.components.source,
    preset: (components.preset as 'shadcn' | 'html' | undefined) ?? init.components.preset,
    defaults: defaults as {
      mode?: 'submit' | 'auto-save';
      ui?: 'shadcn' | 'html';
      overwrite?: boolean;
      serverAction?: boolean;
      formProvider?: boolean;
    },
    fields: config?.fields as Record<string, Record<string, unknown>> | undefined
  });
}

/**
 * Parse a defineConfig(...) TypeScript string back to a PlaygroundConfig.
 * Handles both `defineConfig({...})` wrapper and bare JSON `{...}`.
 * Extracts structured data from the full TS source.
 */
export function parseConfigFromTs(source: string): ConfigParseResult {
  try {
    // Extract the object literal from defineConfig(...)
    let jsonStr = source.trim();

    // Strip imports and export default prefix
    const configMatch = jsonStr.match(/defineConfig(?:<[^>]*>)?\s*\(([\s\S]*)\)\s*;?\s*$/);
    if (configMatch?.[1]) {
      jsonStr = configMatch[1].trim();
    } else {
      // Try bare JSON
      jsonStr = jsonStr.trim();
    }

    // Convert JS object literal to JSON (handle unquoted keys, trailing commas, single quotes, spreads)
    let normalized = jsonStr
      // Remove spread expressions (e.g. ...SHADCN_OVERRIDES) — not representable in JSON
      .replace(/\.\.\.\w+,?\s*/g, '')
      // Replace single quotes with double quotes
      .replace(/'/g, '"')
      // Add quotes around unquoted keys
      .replace(/(\s*)(\w+)\s*:/g, '$1"$2":')
      // Remove trailing commas before } or ]
      .replace(/,\s*([\]}])/g, '$1');

    const parsed = JSON.parse(normalized);
    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
      return { ok: false, error: 'Config must be an object' };
    }

    const config: PlaygroundConfig = {};
    if (
      parsed.components &&
      typeof parsed.components === 'object' &&
      !Array.isArray(parsed.components)
    ) {
      config.components = parsed.components as Record<string, unknown>;
    }
    if (parsed.fields && typeof parsed.fields === 'object' && !Array.isArray(parsed.fields)) {
      config.fields = parsed.fields as Record<string, unknown>;
    }
    if (parsed.defaults && typeof parsed.defaults === 'object' && !Array.isArray(parsed.defaults)) {
      config.defaults = parsed.defaults as Record<string, unknown>;
    }

    return { ok: true, config };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : 'Invalid config syntax' };
  }
}
